version: "3.9"
services:
    health-check:
        build:
            context: .
        container_name: health-check
        volumes:
            - ./config:/usr/src/app/config
        command: ["node", "dist/main.js", "config/endpoints.yaml"]
